[project]
name = "hOCG_H"
version = "1.1"
description = "hOCG_H"
dependencies = [
  "flet==0.80.5",
  "pillow==12.1.0",
  "requests==2.32.5",
  "openpyxl==3.1.5",
  "beautifulsoup4==4.14.3",
]

[tool.flet]
product = "hOCG_H"
org = "com.smalltyrant"
bundle_id = "com.smalltyrant.hocghelper"

[tool.flet.ios]
# iOS release testing build (for AltStore re-signing)
export_method = "release-testing"

[tool.flet.ios.info]
CFBundleDisplayName = "hOCG_H"
CFBundleName = "hOCG_H"

[tool.flet.splash]
ios = false
